name: Requirements Node backend

on:
  workflow_call:
    inputs:      
      build-command:
        default: 'npm ci'
        required: false
        type: string
      test-command:
        default: 'npm run test:only && npm run coverage && npm run coverage:report'
        required: false
        type: string

jobs:

  environment-files-changed:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
  build-test-sonar:
    continue-on-error: true
    runs-on: ubuntu-latest    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      - name: Run command
        run: |
          echo "llego ${{inputs.build-command}}"
          ls && pwd
    
